/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Grade;
import servide.GradeDAO;

/**
 *
 * @author DELL
 */
public class QuanLyDiemJFrame extends javax.swing.JFrame {
    GradeDAO service = new GradeDAO();
    DefaultTableModel model = new DefaultTableModel();
    int index = -1;
    
    /**
     * Creates new form QuanLyDiemJFrame
     */
    public QuanLyDiemJFrame() {
        initComponents();
        setLocationRelativeTo(null);      
        this.filltable(service.getALL());
    }
    void filltable(List<Grade> list){
        model= (DefaultTableModel) data.getModel();
        model.setRowCount(0);
        for (Grade item : list) {
            model.addRow(item.todatarow());
        }
    }
    boolean testdata(){
        if(Txt_masv.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "masv khong dc trong");
            return false;
        }       
        if(Txt_tinhoc.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "tin hoc khong dc trong");
            return false;
        }else{
            try {
                if(Double.parseDouble(Txt_tinhoc.getText())<0){
                    JOptionPane.showMessageDialog(this, "tin hoc phai lon 0");
                    return false;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "tin hoc phai la  so");
                return false;
            }
        }
        if(Txt_GDTC.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "gdtc khong dc trong");
            return false;
        }else{
            try {
                if(Double.parseDouble(Txt_GDTC.getText())<0){
                    JOptionPane.showMessageDialog(this, "gdtc phai lon 0");
                    return false;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "gdtc phai la  so");
                return false;
            }
        }
        if(Txt_tienganh.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "tieng anh khong dc trong");
            return false;
        }else{
            try {
                if(Double.parseDouble(Txt_tienganh.getText())<0){
                    JOptionPane.showMessageDialog(this, "tieng anh phai lon 0");
                    return false;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "tieng anh phai la  so");
                return false;
            }
        }
        return true;
    }
    Grade readfrom(){       
        String masv = Txt_masv.getText();
        double tienganh = Double.parseDouble(Txt_tienganh.getText());
        double tinhoc = Double.parseDouble(Txt_tinhoc.getText());
        double GDTC = Double.parseDouble(Txt_GDTC.getText());
        return new Grade( masv, tinhoc, GDTC, tienganh);
    }
    void showdata(int index){
        Grade sv = service.getALL().get(index);
        Txt_masv.setText(sv.getMasv());
        Txt_tienganh.setText(sv.getTienganh()+"");
        Txt_tinhoc.setText(sv.getTinhoc()+"");
        Txt_GDTC.setText(sv.getGDTC()+"");
        Txt_diemTB.setText(sv.diemtrungbinh()+"");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Txt_FindMa = new javax.swing.JTextField();
        Tbl_findma = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Txt_masv = new javax.swing.JTextField();
        Txt_tienganh = new javax.swing.JTextField();
        Txt_tinhoc = new javax.swing.JTextField();
        Txt_GDTC = new javax.swing.JTextField();
        Btl_new = new javax.swing.JButton();
        Btl_save = new javax.swing.JButton();
        Btl_delete = new javax.swing.JButton();
        Btl_update = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        data = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        Txt_diemTB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Quản Lý Điểm Sinh Viên");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setBackground(new java.awt.Color(255, 51, 153));
        jLabel2.setText("Ma SV");

        Tbl_findma.setText("Find");
        Tbl_findma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tbl_findmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Txt_FindMa, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(Tbl_findma)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Txt_FindMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tbl_findma))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText("Mã SV");

        jLabel5.setText("Tiếng ANh");

        jLabel6.setText("Tin Học");

        jLabel7.setText("GDTC");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Txt_masv)
                    .addComponent(Txt_tienganh)
                    .addComponent(Txt_tinhoc)
                    .addComponent(Txt_GDTC, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Txt_masv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Txt_tienganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Txt_tinhoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Txt_GDTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        Btl_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Add.png"))); // NOI18N
        Btl_new.setText("New");
        Btl_new.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btl_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btl_newActionPerformed(evt);
            }
        });

        Btl_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save as.png"))); // NOI18N
        Btl_save.setText("Save");
        Btl_save.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btl_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btl_saveActionPerformed(evt);
            }
        });

        Btl_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete.png"))); // NOI18N
        Btl_delete.setText("Delete");
        Btl_delete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btl_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btl_deleteActionPerformed(evt);
            }
        });

        Btl_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Edit.png"))); // NOI18N
        Btl_update.setText("Update");
        Btl_update.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btl_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btl_updateActionPerformed(evt);
            }
        });

        data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ma SV", "Tin học", "GDTC", "tieng anh", "diem trung binh"
            }
        ));
        data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(data);

        jLabel8.setText("điểm TB :");

        Txt_diemTB.setBackground(new java.awt.Color(255, 255, 255));
        Txt_diemTB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Txt_diemTB.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txt_diemTB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btl_new, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Btl_update, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                        .addComponent(Btl_delete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btl_save, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txt_diemTB, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btl_new)
                .addGap(18, 18, 18)
                .addComponent(Btl_save)
                .addGap(18, 18, 18)
                .addComponent(Btl_delete)
                .addGap(18, 18, 18)
                .addComponent(Btl_update)
                .addGap(88, 88, 88))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btl_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btl_newActionPerformed
        // TODO add your handling code here:
        Txt_diemTB.setText("");
        Txt_FindMa.setText("");
        Txt_masv.setText("");      
        Txt_tinhoc.setText("");
        Txt_GDTC.setText("");
        Txt_tienganh.setText("");
    }//GEN-LAST:event_Btl_newActionPerformed

    private void Btl_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btl_saveActionPerformed
        // TODO add your handling code here:
        if(this.testdata()){
            Grade sv = this.readfrom();
            if(service.addsv(sv)>0){
                JOptionPane.showMessageDialog(this, "them thanh cong");
                this.filltable(service.getALL());
            }else{
                JOptionPane.showMessageDialog(this, "them that bai !!");
            }
        }
    }//GEN-LAST:event_Btl_saveActionPerformed

    private void Btl_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btl_deleteActionPerformed
        // TODO add your handling code here:
        index = data.getSelectedRow();
        String ma = data.getValueAt(index, 0).toString();
        if(service.delete(ma)>0){
            JOptionPane.showMessageDialog(this, "xoa thanh cong");
            this.filltable(service.getALL());
        }else{
            JOptionPane.showMessageDialog(this, "xoa that bai");
        }
    }//GEN-LAST:event_Btl_deleteActionPerformed

    private void dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataMouseClicked
        // TODO add your handling code here:
        index = data.getSelectedRow();
        this.showdata(index);
    }//GEN-LAST:event_dataMouseClicked

    private void Btl_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btl_updateActionPerformed
        // TODO add your handling code here:
        if(this.testdata()){
            index = data.getSelectedRow();
            String ma = data.getValueAt(index, 0).toString();
            ma ="%"+ma+"%";
            Grade sv = this.readfrom();
            if(service.update(sv, ma)>0){
                JOptionPane.showMessageDialog(this, "update thanh cong");
                this.filltable(service.getALL());
            }else{
                JOptionPane.showMessageDialog(this, "update khong thanh cong");
            }
        }
    }//GEN-LAST:event_Btl_updateActionPerformed

    private void Tbl_findmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tbl_findmaActionPerformed
        // TODO add your handling code here:
        String masv = Txt_FindMa.getText();
        if(masv.isEmpty()){
            JOptionPane.showMessageDialog(this, "ban chua nhap ma");
        }else{
            masv ="%"+masv+"%";
            if(service.findMA(masv).size()>0){
                JOptionPane.showMessageDialog(this, "tim dc");
                this.filltable(service.findMA(masv));
            Txt_diemTB.setText("");           
            Txt_masv.setText("");      
            Txt_tinhoc.setText("");
            Txt_GDTC.setText("");
            Txt_tienganh.setText("");
            }else{
                JOptionPane.showMessageDialog(this, "khong tim thay ma");
                model = (DefaultTableModel) data.getModel();
                model.setRowCount(0);
            }
        }
    }//GEN-LAST:event_Tbl_findmaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyDiemJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyDiemJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyDiemJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyDiemJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyDiemJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btl_delete;
    private javax.swing.JButton Btl_new;
    private javax.swing.JButton Btl_save;
    private javax.swing.JButton Btl_update;
    private javax.swing.JButton Tbl_findma;
    private javax.swing.JTextField Txt_FindMa;
    private javax.swing.JTextField Txt_GDTC;
    private javax.swing.JLabel Txt_diemTB;
    private javax.swing.JTextField Txt_masv;
    private javax.swing.JTextField Txt_tienganh;
    private javax.swing.JTextField Txt_tinhoc;
    private javax.swing.JTable data;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
