CREATE TABLE NghanhHoc
(
  Ma_Nghanh NVARCHAR(10) PRIMARY KEY,
  Ten_Nganh NVARCHAR(50) NOT NULL
);

CREATE TABLE LopHoc
(
  Ma_Lop NVARCHAR(10) PRIMARY KEY,
  Ma_Nghanh NVARCHAR(10) NOT NULL,
  Ten_Lop NVARCHAR(50) NOT NULL,
  FOREIGN KEY (Ma_Nghanh) REFERENCES NghanhHoc(Ma_Nghanh)
);

CREATE TABLE SinhVien
(
  Ma_SV NVARCHAR(10) PRIMARY KEY,
  Ma_Lop NVARCHAR(10) NOT NULL,
  Ho_Ten NVARCHAR(50) NOT NULL,
  Dia_Chi NVARCHAR(50) NOT NULL,
  Email NVARCHAR(50) NOT NULL,
  SDT NVARCHAR(15) NOT NULL,
  Ngay_Sinh DATE NOT NULL,
  Ngay_Het_Han DATE NOT NULL,
  FOREIGN KEY (Ma_Lop) REFERENCES LopHoc(Ma_Lop)
);

CREATE TABLE PhieuMuon
(
  So_Phieu NVARCHAR(10) PRIMARY KEY,
  Ma_SV NVARCHAR(10) NOT NULL,
  Ngay_Muon DATE NOT NULL,
  FOREIGN KEY (Ma_SV) REFERENCES SinhVien(Ma_SV)
);

CREATE TABLE TheLoai
(
  Ma_TL NVARCHAR(10) PRIMARY KEY,
  Ten_TL NVARCHAR(50) NOT NULL
);

CREATE TABLE Sach
(
  Ma_Sach NVARCHAR(10) PRIMARY KEY,
  Ma_TL NVARCHAR(10) NOT NULL,
  Tieu_De NVARCHAR(50) NOT NULL,
  So_Trang INT NOT NULL,
  SoLuong_BanSao INT NOT NULL,
  Gia_Ban MONEY NOT NULL,
  Ngay_Nhap_Kho DATE NOT NULL,
  Nha_Xuat_Ban NVARCHAR(50) NOT NULL,
  Vi_Tri NVARCHAR(50) NOT NULL,
  Nhan_Xet NVARCHAR(50) NOT NULL,
  FOREIGN KEY (Ma_TL) REFERENCES TheLoai(Ma_TL)
);

CREATE TABLE TacGia
(
  Ma_TG NVARCHAR(10) PRIMARY KEY,
  HoTen_TG NVARCHAR(30) NOT NULL,
  ButDanh_TG NVARCHAR(50) NOT NULL,
  Dia_Chi NVARCHAR(50) NOT NULL,
  SDT NVARCHAR(15) NOT NULL
);

CREATE TABLE ChiTietPhieuMuon
(
  Ma_Sach NVARCHAR(10) NOT NULL PRIMARY KEY,
  So_Phieu NVARCHAR(10) NOT NULL PRIMARY KEY ,
  SoLuong INT NOT NULL,
  FOREIGN KEY (Ma_Sach) REFERENCES Sach(Ma_Sach),
  FOREIGN KEY (So_Phieu) REFERENCES PhieuMuon(So_Phieu)
);

CREATE TABLE TacGia_Sach
(
  Id INT PRIMARY KEY ,
  Ma_Sach NVARCHAR(10) NOT NULL,
  Ma_TG NVARCHAR(10) NOT NULL,
  FOREIGN KEY (Ma_Sach) REFERENCES Sach(Ma_Sach),
  FOREIGN KEY (Ma_TG) REFERENCES TacGia(Ma_TG)
);
