USE master
GO

CREATE DATABASE QLDT
GO

USE QLDT
GO

CREATE TABLE GIAOVIEN (
	MaGV NVARCHAR(20) PRIMARY KEY,
	HoTen NVARCHAR(50) ,
	NgaySinh NVARCHAR(30),
	QueQuan NVARCHAR(50),
	GioiTinh NVARCHAR (10)
);
GO
CREATE TABLE DETAI(
	MaDT NVARCHAR(20) PRIMARY KEY,
	TenDT NVARCHAR(50),
	NhanHieu NVARCHAR(50),
	MaGV NVARCHAR(20) ,
	FOREIGN  KEY (MaGV) REFERENCES GIAOVIEN(MaGV)
);
GO
CREATE TABLE SINHVIEN (
	MaSV NVARCHAR(20) PRIMARY KEY,
	HoTen NVARCHAR(50) ,
	NGAYSINH NVARCHAR(20),
	QueQuan NVARCHAR(50),
	Diem  INT ,
	MaDT NVARCHAR(20),
	FOREIGN  KEY (MaDT) REFERENCES DETAI(MaDT)
);
GO
INSERT INTO GIAOVIEN(MaGV,HoTen,NgaySinh,QueQuan,GioiTinh)
VALUES 
		('GV01', 'Trần Thị Loan','6/5/1978','Nam Định','Nữ'),
		('GV02', 'Lê Viết Thịnh','5/03/1989','Hà Tĩnh','Nam'),
		('GV03', 'Trần Hữu Thiện','9/01/1991','Hà Nội','Nam');
GO
INSERT INTO DETAI (MaDT,TenDT,NhanHieu,MaGV)
VALUES 
		('DT01','Công nghệ 4,0',2017,'GV01'),
		('DT02','Công  nghệ Bloackchain',2018,'GV02'),
		('DT03','Bitcoin',2019,'GV03');
GO
INSERT INTO SINHVIEN (MaSV,HoTen,NGAYSINH,QueQuan,Diem,MaDT)
VALUES
		('SV01','LÊ QUANG TÈO','1/1/2000','Hà nội',7,'DT02'),
		('SV02','Đỗ Mỹ Linh','5/08/1998','Hà tĩnh',10,'DT01'),
		('SV03','Mai phương thùy','6/9/1999','Nghệ an',8,'DT02');
go
SELECT * FROM GIAOVIEN
SELECT * FROM DETAI
SELECT * FROM SINHVIEN
go
--2
SELECT SV.MaSV , SV.HoTen, DT.TenDT
FROM GIAOVIEN GV 
JOIN DETAI DT ON GV.MaGV = DT.MaGV
JOIN SINHVIEN SV ON DT.MaDT = SV.MaDT
WHERE GV.HoTen = 'Trần Thị Loan'

--3 
SELECT MaSV,HoTen,DATEDIFF(YEAR, NGAYSINH,GETDATE()) AS TUOI
FROM SINHVIEN
WHERE DATEDIFF (YEAR, NGAYSINH, GETDATE()) > 18 AND QueQuan = 'Hà nội'
--4
