CREATE DATABASE QLNV
DROP  DATABASE QLNV
CREATE TABLE NHANVIEN(
	ID INT PRIMARY KEY,
	HO NVARCHAR(50),
	TEN NVARCHAR(50),
	NGAYSINH DATE NOT NULL,
	LUONG INT,
	PHG NVARCHAR(50)
);
CREATE TABLE PHONGBAN(
	MAPB INT PRIMARY KEY,
	ID INT ,
	TEN NVARCHAR(50),
	MOTA NVARCHAR(100),
	FOREIGN KEY (ID) REFERENCES NhanVien(ID)
);