CREATE TABLE LoaiSach (
    MaLoaiSach NVARCHAR(20) PRIMARY KEY,
    TenLoaiSach NVARCHAR(100) NOT NULL
);

CREATE TABLE Sach (
    MaSach NVARCHAR(20) PRIMARY KEY,
    TieuDe NVARCHAR(100) NOT NULL,
    NXB NVARCHAR(50) NOT NULL,
    TacGia NVARCHAR(50) NOT NULL,
    SoTrang INT NOT NULL,
    SoLuongBanSao INT NOT NULL,
    GiaTien DECIMAL(20,5) NOT NULL,
    NgayNhapKho DATE NOT NULL,
    ViTriDatSach NVARCHAR(30) NOT NULL,
    MaLoaiSach NVARCHAR(20) NOT NULL,
    FOREIGN KEY (MaLoaiSach) REFERENCES LoaiSach(MaLoaiSach)
);

CREATE TABLE SinhVien (
    MaSV NVARCHAR(20) PRIMARY KEY,
    TenSV NVARCHAR(50) NOT NULL,
    MaLop NVARCHAR(20) NOT NULL,
    NgayHetHan DATE NOT NULL,
    ChuyenNghanh NVARCHAR(50) NOT NULL,
    Email NVARCHAR(50) NOT NULL,
    SDT INT NOT NULL
);

CREATE TABLE PhieuMuon (
    MaSoPhieu NVARCHAR(20) PRIMARY KEY,
    TenSV NVARCHAR(50),
    MaSV NVARCHAR(20),
    MaLop NVARCHAR(20),
    MaSach NVARCHAR(20),
    NgayMuon DATE NOT NULL,
    NgayHetHan DATE NOT NULL,
    GhiChu NVARCHAR(100),
    FOREIGN KEY (TenSV) REFERENCES SinhVien (TenSV),
    FOREIGN KEY (MaSV) REFERENCES SinhVien (MaSV),
    FOREIGN KEY (MaLop) REFERENCES SinhVien (MaLop),
    FOREIGN KEY (MaSach) REFERENCES Sach (MaSach)
);
