/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;
import javax.swing.DefaultBoundedRangeModel;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

import model.SinhVien;
import service.SinhVienService;

/**
 *
 * @author dungn
 */
public class View_SinhVien extends javax.swing.JFrame {
    private SinhVienService service = new SinhVienService();
    private DefaultTableModel mol = new DefaultTableModel();
    private int index = -1;
    
    /**
     * Creates new form Table_1
     */
    public View_SinhVien() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.fillTable(service.getAll());
        // đổ dữ liệu từ data sang bảng
        if (Table.getRowCount() > 0) {
        Table.setRowSelectionInterval(0, 0);
    }

    }

    void fillTable(List<SinhVien> list ) {
        mol= (DefaultTableModel)Table.getModel();
        mol.setRowCount(0);
        for(SinhVien x: list){
            mol.addRow(x.toDataRow());
        }
    }

    void showData(int index){
        //lấy đối tượng sinh viên tại vị trí index
        SinhVien sv = service.getAll().get(index);
        txtID.setText(String.valueOf(sv.getID()));
        txtNAME.setText(sv.getName());
        //mếu combo: getSelectedItem
        // nếu Radio: if else
    }

    SinhVien readForm(){
        int id = Integer.parseInt(txtID.getText().trim());
        String name = txtNAME.getText().trim();
        return new SinhVien(id, name);
    }
    
    boolean testData(){
       if(txtID.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Fall");
            return false;
       }
       else { //đã có dữ liệu check: id là số? ,id>=0
            try {//là số
                 if(Integer.parseInt(txtID.getText())<0);
            } catch (Exception e) { // khong la so
                JOptionPane.showMessageDialog(this," id khong phai so");
                return false;
            }
           // check name
           if(txtNAME.getText().isEmpty()){
                JOptionPane.showMessageDialog(this,"name trong");
                return false;
           }else{ //checktenchu cai :k ap dungtieng viet
            if(!txtNAME.getText().matches("[a-zA-Z ]+")){ // nếu có lỗi sẽ báo sai định dạng
                JOptionPane.showMessageDialog(this,"name sai dinh dang");
                return false;
            }
           }
           return true;
       }
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNAME = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        btnADD = new javax.swing.JButton();
        btnUPDATE = new javax.swing.JButton();
        btnDELETE = new javax.swing.JButton();
        btnFIND = new javax.swing.JButton();
        btnSORT = new javax.swing.JButton();
        btnRESET = new javax.swing.JButton();
        btnFindName = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        jLabel2.setText("Name");

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "NAME"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        btnADD.setText("ADD");
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });

        btnUPDATE.setText("UPDATE");
        btnUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPDATEActionPerformed(evt);
            }
        });

        btnDELETE.setText("DELETE");
        btnDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELETEActionPerformed(evt);
            }
        });

        btnFIND.setText("FIND");
        btnFIND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFINDActionPerformed(evt);
            }
        });

        btnSORT.setText("SORT");
        btnSORT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSORTActionPerformed(evt);
            }
        });

        btnRESET.setText("RESET");

        btnFindName.setText("FindName");
        btnFindName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181)
                        .addComponent(jLabel2)
                        .addGap(45, 45, 45)
                        .addComponent(txtNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnADD)
                                .addGap(59, 59, 59)
                                .addComponent(btnUPDATE)
                                .addGap(30, 30, 30)
                                .addComponent(btnDELETE)
                                .addGap(43, 43, 43)
                                .addComponent(btnFIND)
                                .addGap(45, 45, 45)
                                .addComponent(btnSORT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRESET))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(btnFindName)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnADD)
                    .addComponent(btnUPDATE)
                    .addComponent(btnDELETE)
                    .addComponent(btnSORT)
                    .addComponent(btnFIND)
                    .addComponent(btnRESET))
                .addGap(18, 18, 18)
                .addComponent(btnFindName)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed
        // TODO add your handling code here:
        if(this.testData()){
        SinhVien sv = this.readForm();
        if(service.getSinhVien(sv.getID())!=null) {
            JOptionPane.showMessageDialog(this,"Ma trung k them dc");
        }else{
            
        if(service.addSinhVien(sv)>0){//add đc
            JOptionPane.showMessageDialog(this, "thêm thành công");
            this.fillTable(service.getAll());
        }else{
            JOptionPane.showMessageDialog(this, "thêm k thành công");
        }}}
    }//GEN-LAST:event_btnADDActionPerformed

    private void btnUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPDATEActionPerformed
        // TODO add your handling code here:
        index = Table.getSelectedRow();
        int ID = Integer.parseInt(
            Table.getValueAt(index, 0).toString()
        );
        // lấy đối tượng mới tuỏm
        SinhVien sv = this.readForm();
        if(service.updateSinhVien(ID, sv)> 0){
            JOptionPane.showMessageDialog(this, " thanh cong update");
            this.fillTable(service.getAll());
        }
        else {
            JOptionPane.showMessageDialog(this, "UPDATE THAT BAI");
        }
    }//GEN-LAST:event_btnUPDATEActionPerformed

    private void btnDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELETEActionPerformed
        // TODO add your handling code here:
        index = Table.getSelectedRow();
        int ID = Integer.parseInt(
            Table.getValueAt(index, 0).toString()
        );
        if(service.deleteSinhVien(ID)>0){
            JOptionPane.showMessageDialog(this, "Xoa thanh cong");
            this.fillTable(service.getAll());
        }else {
            JOptionPane.showMessageDialog(this, "xOA THAT BAI");
        }
    }//GEN-LAST:event_btnDELETEActionPerformed

    private void btnFINDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFINDActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt( 
                    JOptionPane.showInputDialog("Moi nhap ma:   "));
        if(service.getSinhVien(id) != null) {
            for(int i = 0; i<Table.getRowCount();i++){
                int gt = Integer.parseInt(Table.getValueAt(i, 0).toString());

                if(gt==id){
                    index=i;
                    break;
                }
            }
            // doing for
            this.showData(index);
            Table.setRowSelectionInterval(index, index);
        }else{
            JOptionPane.showMessageDialog(this, "khong tim thay");
            txtID.setText("");
            txtNAME.setText("");
        }
         
    }//GEN-LAST:event_btnFINDActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
        index = Table.getSelectedRow();
        this.showData(index);
    }//GEN-LAST:event_TableMouseClicked

    private void btnFindNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindNameActionPerformed
        // TODO add your handling code here:
        String name = JOptionPane.showInputDialog(this, "Nhập tên cần tìm kiếm:");
        if (name == null || name.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập tên.");
            return;
        }else{
            name = "%" + name + "%";
            if (service.findName(name).size() > 0)//timf tương đối 
            {
                JOptionPane.showMessageDialog(this, "Tìm được");
                fillTable(service.findName(name));
                txtID.setText("");
                txtNAME.setText("");
            }else{ // khong tìm thấy
                JOptionPane.showMessageDialog(this, "khong tim được");
                mol = (DefaultTableModel) Table.getModel();
                mol.setRowCount(0); // xóa trắng
                txtID.setText("");
                txtNAME.setText("");
            }
            }

           }
//GEN-LAST:event_btnFindNameActionPerformed

    private void btnSORTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSORTActionPerformed
        // TODO add your handling code here:
        List<SinhVien> list = service.SortName();
        fillTable(list);
    }//GEN-LAST:event_btnSORTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_SinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_SinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_SinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_SinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_SinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnDELETE;
    private javax.swing.JButton btnFIND;
    private javax.swing.JButton btnFindName;
    private javax.swing.JButton btnRESET;
    private javax.swing.JButton btnSORT;
    private javax.swing.JButton btnUPDATE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNAME;
    // End of variables declaration//GEN-END:variables
}
