/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Student;
import servide.StudentDAO;

/**
 *
 * @author DELL
 */
public class SinhVienJFrame extends javax.swing.JFrame {
    StudentDAO service = new StudentDAO();
    DefaultTableModel model = new DefaultTableModel();
    int index = -1;
    /**
     * Creates new form SinhVienJFrame
     */
    public SinhVienJFrame() {
        initComponents();
        Txt_anh.setBackground(Color.ORANGE);
        Txt_anh.setOpaque(true);
        fillTable();
    }
    public void fillTable(){
        DefaultTableModel model = (DefaultTableModel) data.getModel();
        String[] columNames = {"mã sv","Họ Tên","Email","sdt","gioi tinh","dia chi","hinh anh"};
        model.setColumnIdentifiers(columNames);
        ArrayList<Student> list = StudentDAO.viewAll();
        model.setRowCount(0);
        for (Student st : list) {
            Object[] rowDATA = {st.getMasv(),st.getHoten(),st.getEmail(),st.getSodt(),st.getGioitinh(),st.getDiachi(),st.getHinh()};
            model.addRow(rowDATA);
        }
        
        
    }
    void showdata(int index){
        Student sv = service.viewAll().get(index);
        Txt_Masv.setText(sv.getMasv());
        Txt_hoten.setText(sv.getHoten());
        Txt_email.setText(sv.getEmail());
        Txt_sodienthoai.setText(sv.getSodt()+"");
        if(sv.getGioitinh()){
            Radio_nam.setSelected(true);
        }else{
            Radio_nu.setSelected(true);
        }
        Txt_diachi.setText(sv.getDiachi());
        
        
    }
    Student readFrom(){      
        String masv = Txt_Masv.getText();
        String hoten =Txt_hoten.getText();
        String email = Txt_email.getText();
        int sdt = Integer.parseInt(Txt_sodienthoai.getText());
        boolean gioitinh;
        if(Radio_nam.isSelected()){
            gioitinh = true;
        }else{
            gioitinh = false;
        }
        String diachi = Txt_diachi.getText();
        return new Student(masv, hoten, email, sdt, gioitinh, diachi, diachi);
    }
    boolean testdata(){
        if(Txt_Masv.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "ma sach khong dc de trong");
            return false;
        }
        if(Txt_hoten.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "ho ten khong dc de trong");
            return false;
        }
        if(Txt_email.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "email khong dc de trong");
            return false;
        }
        if(Txt_sodienthoai.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "so dien thoai khong dc de trong");
            return false;
        }
        if(Txt_diachi.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "dia chi khong dc de trong");
            return false;
        }
        if(Txt_sodienthoai.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "ma sach khong dc de trong");
            return false;
        }else{
            try {
                if(Integer.parseInt(Txt_sodienthoai.getText())<0 || Txt_sodienthoai.getText().length() != 9){
                    JOptionPane.showMessageDialog(this, "so dien thoai phai co 9 so");
                    return false;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "so dien thoai phai  la so");
            }
        }
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Radio_nam = new javax.swing.JRadioButton();
        Radio_nu = new javax.swing.JRadioButton();
        Txt_Masv = new javax.swing.JTextField();
        Txt_hoten = new javax.swing.JTextField();
        Txt_email = new javax.swing.JTextField();
        Txt_sodienthoai = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        data = new javax.swing.JTable();
        Txt_anh = new javax.swing.JLabel();
        Btl_new = new javax.swing.JButton();
        Btl_save = new javax.swing.JButton();
        Btl_update = new javax.swing.JButton();
        Btl_delete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Txt_diachi = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Quản Lý Sinh Viên");

        jLabel2.setText("Ma SV :");

        jLabel3.setText("Họ Tên :");

        jLabel4.setText("Email  :");

        jLabel5.setText("Số ĐT :");

        jLabel6.setText("Giới Tính");

        buttonGroup1.add(Radio_nam);
        Radio_nam.setText("Nam");

        buttonGroup1.add(Radio_nu);
        Radio_nu.setText("Nữ");

        data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Ma sv", "ho ten", "email", "so dt", "gioi tinh", "dia chi", "anh"
            }
        ));
        data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(data);

        Txt_anh.setBackground(new java.awt.Color(204, 204, 204));
        Txt_anh.setText("anh");
        Txt_anh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Txt_anh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Txt_anhMouseClicked(evt);
            }
        });

        Btl_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Add.png"))); // NOI18N
        Btl_new.setText("New");
        Btl_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btl_newActionPerformed(evt);
            }
        });

        Btl_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save.png"))); // NOI18N
        Btl_save.setText("Save");
        Btl_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btl_saveActionPerformed(evt);
            }
        });

        Btl_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Edit.png"))); // NOI18N
        Btl_update.setText("Update");
        Btl_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btl_updateActionPerformed(evt);
            }
        });

        Btl_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete.png"))); // NOI18N
        Btl_delete.setText("Delete");
        Btl_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btl_deleteActionPerformed(evt);
            }
        });

        jLabel8.setText("Địa chỉ");

        Txt_diachi.setColumns(20);
        Txt_diachi.setRows(5);
        jScrollPane2.setViewportView(Txt_diachi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Radio_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Radio_nu, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_Masv, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_sodienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(Txt_anh, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btl_save, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btl_new, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btl_update)
                    .addComponent(Btl_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(Btl_new)
                        .addGap(18, 18, 18)
                        .addComponent(Btl_save)
                        .addGap(18, 18, 18)
                        .addComponent(Btl_update)
                        .addGap(18, 18, 18)
                        .addComponent(Btl_delete))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(Txt_Masv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(Txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(Txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(Txt_sodienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(Radio_nam)
                                    .addComponent(Radio_nu)))
                            .addComponent(Txt_anh, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btl_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btl_saveActionPerformed
        // TODO add your handling code here:
        if(this.testdata()){
        Student sv = this.readFrom();
        if(service.addSV(sv)> 0){
            JOptionPane.showMessageDialog(this, "them thanh cong");
            fillTable();
        }else{
            JOptionPane.showMessageDialog(this, "that bai");
        }
        }
    }//GEN-LAST:event_Btl_saveActionPerformed

    private void dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataMouseClicked
        // TODO add your handling code here:
        index = data.getSelectedRow();
        this.showdata(index);
    }//GEN-LAST:event_dataMouseClicked

    private void Btl_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btl_newActionPerformed
        // TODO add your handling code here:
        Txt_Masv.setText("");
        Txt_hoten.setText("");
        Txt_email.setText("");
        Txt_sodienthoai.setText("");
        Txt_anh.setText("");
        Txt_diachi.setText("");
    }//GEN-LAST:event_Btl_newActionPerformed

    private void Btl_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btl_updateActionPerformed
        // TODO add your handling code here:
        if(this.testdata()){
            index = data.getSelectedRow();
            String ma = data.getValueAt(index, 0).toString();
            ma ="%"+ma+"%";
            Student sv = this.readFrom();
            if(service.update(sv, ma)>0){
                JOptionPane.showMessageDialog(this, "update thanh cong");
                fillTable();
            }else{
                JOptionPane.showMessageDialog(this, "update khong thanh cong");
            }
        }
    }//GEN-LAST:event_Btl_updateActionPerformed

    private void Btl_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btl_deleteActionPerformed
        // TODO add your handling code here:
        index = data.getSelectedRow();
        String ma = data.getValueAt(index, 0).toString();
        if(service.delete(ma)>0){
            JOptionPane.showMessageDialog(this, "delete thanh cong");
            fillTable();
            
        }else{
            JOptionPane.showMessageDialog(this, "delete khong thanh cong");
        }
    }//GEN-LAST:event_Btl_deleteActionPerformed

    private void Txt_anhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_anhMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_anhMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SinhVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SinhVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SinhVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinhVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SinhVienJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btl_delete;
    private javax.swing.JButton Btl_new;
    private javax.swing.JButton Btl_save;
    private javax.swing.JButton Btl_update;
    private javax.swing.JRadioButton Radio_nam;
    private javax.swing.JRadioButton Radio_nu;
    private javax.swing.JTextField Txt_Masv;
    private javax.swing.JLabel Txt_anh;
    private javax.swing.JTextArea Txt_diachi;
    private javax.swing.JTextField Txt_email;
    private javax.swing.JTextField Txt_hoten;
    private javax.swing.JTextField Txt_sodienthoai;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable data;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
